title: "Yudha Setiawan"
description: "Always try to expecting different result"
keywords: "html5, jquery, tutorials, image gallery, plugins, web design, tutorial, php, css, css3, javascript, php login system, programming, mysql, web development, resources, buttons, free, downloads, iphone, freebies, news, html, freelance"
url: "http://yudhasetiawan.com"
timezone: "Asia/Jakarta"
quotes:
  - "I promise!"
  - "Always try to expecting different result."
  - "Keep your balance, You must keep moving."
  - "Now or never."
google:
  uid: "37180411"
  analytics: "UA-37180411-3"
author:
  name: "Yudha Setiawan"
  url: "http://yudhasetiawan.com"
  email: "me@yudhasetiawan.com"
  address:
    locality: Yogyakarta
    country: Indonesia
  socials:
    - name: "linkedin"
      title: "Linkedin"
      icon: "circlelinkedin"
      url: "http://id.linkedin.com/in/yudhasetiawan"
emoji:
  src: "/assets/img/emoji"
permalink: pretty
highlighter: rouge
sass:
  sass_dir: assets
  style: :compressed
gems:
  - jemoji
  - jekyll-mentions
